# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_cpp <- function(ds, B = 1000L) {
    .Call(`_STAT600_bootstrap_cpp`, ds, B)
}

rcpparma_hello_world <- function() {
    .Call(`_STAT600_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_STAT600_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_STAT600_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_STAT600_rcpparma_bothproducts`, x)
}

